/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.produtoCategoria;

import controller.ProdutoCategoriaDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ProdutoCategoria;

/**
 *
 * @author Usuario
 */
public class GerenciarProdutoCategoria extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarProdutoCategoria
     */
    public GerenciarProdutoCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarPorNome = new javax.swing.JTextField();
        jButtonMostrarTodos = new javax.swing.JButton();
        jButtonCadastrarProdutoCategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutoCategoria = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar categoria de produto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciar Categoria de Produto");

        jLabel2.setText("Pesquisar por nome:");

        jTextFieldPesquisarPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarPorNomeKeyReleased(evt);
            }
        });

        jButtonMostrarTodos.setText("*");
        jButtonMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMostrarTodosMouseReleased(evt);
            }
        });

        jButtonCadastrarProdutoCategoria.setText("Novo");
        jButtonCadastrarProdutoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProdutoCategoriaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem"));

        jTableProdutoCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutoCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutoCategoria);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrarProdutoCategoria)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonMostrarTodos))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCadastrarProdutoCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterar(){
        int linhaSelecionda = jTableProdutoCategoria.getSelectedRow();
        
        if(linhaSelecionda != -1){
            
            //getModel pega a célula
            //getValueAt passa a linha e a coluna, a coluna 0 é o id, assim como a coluna 1 seria o nome
            String id = jTableProdutoCategoria.getModel().
                    getValueAt(linhaSelecionda, 0).toString();
            
            ProdutoCategoriaAlterar ua = new ProdutoCategoriaAlterar();
            ua.setVisible(true);
            ua.mostrarCategoria(id);
        }
    }
    
    private void jTableProdutoCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoCategoriaMouseClicked

        if(evt.getClickCount() == 2){
            this.alterar();
        }
    }//GEN-LAST:event_jTableProdutoCategoriaMouseClicked

    private void jTextFieldPesquisarPorNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarPorNomeKeyReleased
        String campoPesquisa = (jTextFieldPesquisarPorNome.getText().trim());
        
        
        if(!campoPesquisa.equals("")){
            
            
            //table's model
            DefaultTableModel modelo = (DefaultTableModel) jTableProdutoCategoria.getModel();
            
            //Limpa as linhas da tabela
            modelo.setNumRows(0);
            
            try {
                ProdutoCategoriaDao dao = new ProdutoCategoriaDao();
                List<ProdutoCategoria> categorias = dao.buscarUsuario(campoPesquisa);
                
                for(ProdutoCategoria u : categorias){
                    //Cria uma nova linha
                    String novaLinha[] = {
                        String.valueOf(u.getId()),
                        u.getNome(),
                        ""
                    };
                    
                    modelo.addRow(novaLinha); //Adiciona linha na tabela
                }
                
                //DataBase search
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar. " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisarPorNomeKeyReleased

    private void jButtonMostrarTodosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarTodosMouseReleased
        String campoPesquisa = (jTextFieldPesquisarPorNome.getText().trim());
        
        
        if(!campoPesquisa.equals("")){
            
            
            //table's model
            DefaultTableModel modelo = (DefaultTableModel) jTableProdutoCategoria.getModel();
            
            //Limpa as linhas da tabela
            modelo.setNumRows(0);
            
            try {
                ProdutoCategoriaDao dao = new ProdutoCategoriaDao();
                List<ProdutoCategoria> categorias = dao.buscarTodosNomes(campoPesquisa);
                
                for(ProdutoCategoria pc : categorias){
                    //Cria uma nova linha
                    String novaLinha[] = {
                        String.valueOf(pc.getId()),
                        pc.getNome(),
                        ""
                    };
                    
                    modelo.addRow(novaLinha); //Adiciona linha na tabela
                    jTextFieldPesquisarPorNome.setText("");
                    jTextFieldPesquisarPorNome.requestFocus();
                }
                
                //DataBase search
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar. " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonMostrarTodosMouseReleased

    private void jButtonCadastrarProdutoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProdutoCategoriaActionPerformed
        new ProdutoCategoriaCadastrar().setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarProdutoCategoriaActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        this.alterar();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int linhaSelecionada = jTableProdutoCategoria.getSelectedRow();
        
        int opcao = JOptionPane.showConfirmDialog(this, "Confirme a exclusão.");
        
        if(opcao == JOptionPane.YES_OPTION){
            if(linhaSelecionada != -1){
                /*
                    Pega os dados das colunas da tabela
                    Primeira coluna (0 que é o id) é inteiro
                */
                Integer id = Integer.parseInt(jTableProdutoCategoria.getModel().
                        getValueAt(linhaSelecionada, 0).toString());
                System.out.println(id);


                try {
                    ProdutoCategoria pc = new ProdutoCategoria(id, null);
                    ProdutoCategoriaDao dao = new ProdutoCategoriaDao();
                    dao.excluir(pc);

                    //Remove a linha da tabela
                    DefaultTableModel modelo = (DefaultTableModel) jTableProdutoCategoria.getModel();
                    modelo.removeRow(linhaSelecionada);

                    JOptionPane.showMessageDialog(this, "Registro excluido com sucesso.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir o registro" + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o registro.");
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutoCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarProdutoCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrarProdutoCategoria;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutoCategoria;
    private javax.swing.JTextField jTextFieldPesquisarPorNome;
    // End of variables declaration//GEN-END:variables
}
