/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.usuariogrupo;

import controller.UsuarioGrupoDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UsuarioGrupo;

/**
 *
 * @author aluno
 */
public class GerenciarUsuarioGrupo extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarUsuarioGrupo
     */
    public GerenciarUsuarioGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarPorNome = new javax.swing.JTextField();
        jButtonMostrarTodos = new javax.swing.JButton();
        jButtonCadastrarGrupoUsuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarioGrupo = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar grupo de usuário");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciar Grupo de Usuário");

        jLabel2.setText("Pesquisar por nome:");

        jTextFieldPesquisarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarPorNomeActionPerformed(evt);
            }
        });
        jTextFieldPesquisarPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarPorNomeKeyReleased(evt);
            }
        });

        jButtonMostrarTodos.setText("*");
        jButtonMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMostrarTodosMouseReleased(evt);
            }
        });

        jButtonCadastrarGrupoUsuario.setText("Novo");
        jButtonCadastrarGrupoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarGrupoUsuarioActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem"));

        jTableUsuarioGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarioGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioGrupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarioGrupo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostrarTodos)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarGrupoUsuario)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCadastrarGrupoUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarTodos))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUsuarioGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioGrupoMouseClicked

        if(evt.getClickCount() == 2){
            this.alterar();
        }
    }//GEN-LAST:event_jTableUsuarioGrupoMouseClicked

    private void alterar(){
        int linhaSelecionda = jTableUsuarioGrupo.getSelectedRow();
        
        if(linhaSelecionda != -1){
            
            //getModel pega a célula
            //getValueAt passa a linha e a coluna, a coluna 0 é o id, assim como a coluna 1 seria o nome
            String id = jTableUsuarioGrupo.getModel().
                    getValueAt(linhaSelecionda, 0).toString();
            
            UsuarioGrupoAlterar ua = new UsuarioGrupoAlterar();
            ua.setVisible(true);
            ua.mostrarUsuario(id);
        }
    }
    private void jTextFieldPesquisarPorNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarPorNomeKeyReleased
        String campoPesquisa = (jTextFieldPesquisarPorNome.getText().trim());
        
        
        if(!campoPesquisa.equals("")){
            
            
            //table's model
            DefaultTableModel modelo = (DefaultTableModel) jTableUsuarioGrupo.getModel();
            
            //Limpa as linhas da tabela
            modelo.setNumRows(0);
            
            try {
                UsuarioGrupoDao dao = new UsuarioGrupoDao();
                List<UsuarioGrupo> usuarios = dao.buscarUsuario(campoPesquisa);
                
                for(UsuarioGrupo u : usuarios){
                    //Cria uma nova linha
                    String novaLinha[] = {
                        String.valueOf(u.getId()),
                        u.getNome(),
                        ""
                    };
                    
                    modelo.addRow(novaLinha); //Adiciona linha na tabela
                }
                
                //DataBase search
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar. " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisarPorNomeKeyReleased

    private void jButtonCadastrarGrupoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarGrupoUsuarioActionPerformed
        new UsuarioGrupoCadastrar().setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarGrupoUsuarioActionPerformed

    private void jButtonMostrarTodosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarTodosMouseReleased
         String campoPesquisa = (jTextFieldPesquisarPorNome.getText().trim());
        
        
        if(!campoPesquisa.equals("")){
            
            
            //table's model
            DefaultTableModel modelo = (DefaultTableModel) jTableUsuarioGrupo.getModel();
            
            //Limpa as linhas da tabela
            modelo.setNumRows(0);
            
            try {
                UsuarioGrupoDao dao = new UsuarioGrupoDao();
                List<UsuarioGrupo> usuarios = dao.buscarTodosNomes(campoPesquisa);
                
                for(UsuarioGrupo u : usuarios){
                    //Cria uma nova linha
                    String novaLinha[] = {
                        String.valueOf(u.getId()),
                        u.getNome(),
                        ""
                    };
                    
                    modelo.addRow(novaLinha); //Adiciona linha na tabela
                    jTextFieldPesquisarPorNome.setText("");
                }
                
                //DataBase search
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar. " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonMostrarTodosMouseReleased

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int linhaSelecionada = jTableUsuarioGrupo.getSelectedRow();
        
        int opcao = JOptionPane.showConfirmDialog(this, "Confirme a exclusão.");
        
        if(opcao == JOptionPane.YES_OPTION){
            if(linhaSelecionada != -1){
                /*
                    Pega os dados das colunas da tabela
                    Primeira coluna (0 que é o id) é inteiro
                */
                Integer id = Integer.parseInt(jTableUsuarioGrupo.getModel().
                        getValueAt(linhaSelecionada, 0).toString());
                System.out.println(id);


                try {
                    UsuarioGrupo u = new UsuarioGrupo(id, null);
                    UsuarioGrupoDao dao = new UsuarioGrupoDao();
                    dao.excluir(u);

                    //Remove a linha da tabela
                    DefaultTableModel modelo = (DefaultTableModel) jTableUsuarioGrupo.getModel();
                    modelo.removeRow(linhaSelecionada);

                    JOptionPane.showMessageDialog(this, "Registro excluido com sucesso.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir o registro" + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o registro.");
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        this.alterar();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldPesquisarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarPorNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuarioGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuarioGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuarioGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuarioGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarUsuarioGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrarGrupoUsuario;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarioGrupo;
    private javax.swing.JTextField jTextFieldPesquisarPorNome;
    // End of variables declaration//GEN-END:variables
}
